name: Pipelines

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unitTest:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Gradle and JDK
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          java-version: '17'

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: "**/build/test-results/test*/*.xml"
          reporter: java-junit
